/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mahao_jnidemo2_GetFromC */

#ifndef _Included_com_mahao_jnidemo2_GetFromC
#define _Included_com_mahao_jnidemo2_GetFromC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mahao_jnidemo2_GetFromC
 * Method:    dynamicLog
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mahao_jnidemo2_GetFromC_dynamicLog
  (JNIEnv *, jclass);

/*
 * Class:     com_mahao_jnidemo2_GetFromC
 * Method:    staticLog
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mahao_jnidemo2_GetFromC_staticLog
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mahao_jnidemo2_GetFromC
 * Method:    getSubmit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mahao_jnidemo2_GetFromC_getSubmit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mahao_jnidemo2_GetFromC
 * Method:    commonField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mahao_jnidemo2_GetFromC_commonField
  (JNIEnv *, jobject);

/*
 * Class:     com_mahao_jnidemo2_GetFromC
 * Method:    staticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mahao_jnidemo2_GetFromC_staticField
  (JNIEnv *, jobject);

/*
 * Class:     com_mahao_jnidemo2_GetFromC
 * Method:    stringAndInt
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mahao_jnidemo2_GetFromC_stringAndInt
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_mahao_jnidemo2_GetFromC
 * Method:    getUserCalendar
 * Signature: ()Ljava/util/Calendar;
 */
JNIEXPORT jobject JNICALL Java_com_mahao_jnidemo2_GetFromC_getUserCalendar
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
